version: '3.8'

services:
  # Backend сервис
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - CORS_ORIGIN=http://95.164.119.96:3000
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/promocodes:/app/backend/promocodes
      - ./backend/state.json:/app/backend/state.json
      - ./backend/quizStats.json:/app/backend/quizStats.json
    restart: unless-stopped

  # Frontend сервис
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend.simple
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://95.164.119.96:3001
      - REACT_APP_FRONTEND_URL=http://95.164.119.96:3000
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx для проксирования
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped 